spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9999/demo?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: root
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
  resources:
    static-locations: classpath:/static
  mvc:
    favicon:
      enabled: false
  profiles:
    active: test
  jackson:
    time-zone: Asia/Shanghai
    date-format: java.text.SimpleDateFormat
server:
  port: 8080